version: '3.1'

services:

  db:
    image: mysql
    volumes:
      - ./mysql_volume:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: "no"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - ${DB_PORT}:3306

  phpmyadmin:
    image: phpmyadmin
    restart: "no"
    ports:
      - 8080:80
